Add missing message proto dep to V2AlphaPublicApiServer
Add `//src/main/proto/wfa/measurement/internal/reporting/v2:impression_qualification_filter_kt_jvm_proto` to the `deps` of `v2alpha_public_api_server`. This ensures `InternalImpressionQualificationFilter` message class is available at runtime, addressing potential NoClassDefFoundError that might be causing crash loops and integration test timeouts.

Co-authored-by: kungfucraig <700015+kungfucraig@users.noreply.github.com>