Revert "Add a BUILD target for Cloud Spanner Emulator, using it from the spanner_emulator_test macro."
This reverts commit 261a8c94eddf715c865479df2207416bd42f8d74.

Reason for revert: This changes prevents running all tests which use the spanner emulator at the same time. They step on each other and can't find a copy of the instance.

org.wfanet.measurement.db.duchy.gcp.ComputationsSchemaTest
java.util.concurrent.ExecutionException: com.google.cloud.spanner.SpannerException: ALREADY_EXISTS: io.grpc.StatusRuntimeException: ALREADY_EXISTS: Instance already exists: projects/test-project/instances/test-instance

java.util.concurrent.ExecutionException: com.google.cloud.spanner.SpannerException: NOT_FOUND: io.grpc.StatusRuntimeException: NOT_FOUND: Instance not found: projects/test-project/instances/test-instance

Change-Id: I76be1f2f7947a6b542846fed0f1abf72974a9a0a