build: Add python test coverage report (#2128)
All Python tests work fine with bazel test, but [this
test](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/python/wfa/measurement/reporting/postprocessing/tools/test_post_process_origin_report.py)
fails with bazel coverage because it cannot find the protobuf
dependency:

```
from google.protobuf.json_format import Parse
ModuleNotFoundError: No module named 'google'

```
It seems that bazel test and bazel coverage handle the PYTHONPATH
differently.

**bazel test adds:**
```
.../protobuf~
.../protobuf~/python (where the protobuf library is, with the structure that the test expects)
.../protobuf~/python/python
and directories like:
/rules_pythonpip~pip_311_<<dependency declared in the requirements.txt>>
/rules_pythonpip~pip_311_<<dependency declared in the requirements.txt>>/site-packages

```
That protobuf~ directory has this structure:
```
protobuf~/
└── python
    └── google
        └── protobuf

```
**bazel coverage adds:**
```
.../protobuf~
and directories like:
/rules_pythonpip~pip_311_<<dependency declared in the requirements.txt>>
/rules_pythonpip~pip_311_<<dependency declared in the requirements.txt>>/site-packages

```
By adding the dependency in the requirements.txt file, both bazel test
and bazel coverage find protobuf and work fine.